# Generated by Django 2.0.1 on 2018-01-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.BooleanField()),
            ],
        ),
    ]
